
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS IDENTIFIER LBRACE RBRACE STRINGprogram : statementsstatements : statements statementstatements : statementstatement : IDENTIFIER LBRACE attributes RBRACEattributes : attributes attributeattributes : attributeattribute : IDENTIFIER EQUALS STRING'
    
_lr_action_items = {'IDENTIFIER':([0,2,3,5,6,8,9,11,12,13,],[4,4,-3,-2,7,7,-6,-4,-5,-7,]),'$end':([1,2,3,5,11,],[0,-1,-3,-2,-4,]),'LBRACE':([4,],[6,]),'EQUALS':([7,],[10,]),'RBRACE':([8,9,12,13,],[11,-6,-5,-7,]),'STRING':([10,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,5,]),'attributes':([6,],[8,]),'attribute':([6,8,],[9,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',5),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',9),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',13),
  ('statement -> IDENTIFIER LBRACE attributes RBRACE','statement',4,'p_statement','parser.py',17),
  ('attributes -> attributes attribute','attributes',2,'p_attributes_multiple','parser.py',21),
  ('attributes -> attribute','attributes',1,'p_attributes_single','parser.py',25),
  ('attribute -> IDENTIFIER EQUALS STRING','attribute',3,'p_attribute','parser.py',29),
]
